source "$WG_ROOT/lib/common.sh"; source "$WG_ROOT/levels/postgres/lib.sh"
has_table users || fail "users table is gone"
[ "$(sql "select count(*) from users")" = 3 ] || fail "the 3 users must stay"
has_constraint users p || fail "no primary key on users"
has_constraint users u || fail "no unique constraint on users"
has_constraint users c || fail "no check constraint on users"
rejects "insert into users values (1, 'x@example.com', 30)" || fail "duplicate id 1 was accepted"
rejects "insert into users values (9, 'anna@example.com', 30)" || fail "duplicate email was accepted"
rejects "insert into users values (9, 'kid@example.com', 7)" || fail "age 7 was accepted"
sql "insert into users values (9, 'ok@example.com', 30); delete from users where id = 9" >/dev/null || fail "a valid row (9, ok@example.com, 30) was rejected"
ok "users: primary key, unique email, age check"
