source "$WG_ROOT/levels/nestjs/nest.sh"
boot_or_fail
[ "$(code $BASE/users/999)" = 404 ] || fail "GET /users/999 should stay 404"
b=$(get /users/999); echo "$b" | grep -q '"path":"/users/999"' || fail "404 body has no path: $b"
echo "$b" | grep -q '"statusCode":404' || fail "404 body has no statusCode"
echo "$b" | grep -qi 'not found' || fail "404 body lost its message"
[ "$(code $BASE/users/abc)" = 400 ] || fail "GET /users/abc should stay 400"
get /users/abc | grep -q '"path":"/users/abc"' || fail "400 body has no path"
get /users/1 | grep -q "Ada Lovelace" || fail "GET /users/1 broken"
grep -q 'APP_FILTER' "$APP/src/app.module.ts" || fail "bind the filter via APP_FILTER in AppModule"
ok "error bodies carry the path"
