{{- if not .Values.db.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  password: {{ required "db.password or db.existingSecret is required" .Values.db.password | quote }}
{{- end }}
